#!/bin/bash

baseDir="$( cd "$(dirname "$0")" && pwd )"
cd "$baseDir"

COL_OFF="\033[0m"
COL_BOLD="\033[01;01m"
COL_RED="\033[31m"
COL_GREEN="\033[32m"
COL_BLUE="\033[34;01m"

function safe_execute {
  echo -e "\n[....] $*"
  $*
  if [[ $? -eq 0 ]]; then
    echo -e "[${COL_GREEN} OK ${COL_OFF}] $*"
  else
    echo -e "[${COL_RED}FAIL${COL_OFF}] $*" >&2
    echo -e "[${COL_RED}CRIT${COL_OFF}] ABORTING..." >&2
    exit 1
  fi
}

for module in *; do
  if [[ -f "$module/package.json" ]]; then
    # go to module dir
    cd $module
    echo -e "[    ] ${COL_BLUE}switching to ${module}${COL_OFF}"

    safe_execute npm $*

    cd "$baseDir"
  fi
done
