#!/bin/bash

baseDir="$( cd "$(dirname "$0")" && pwd )"
cd "$baseDir"

# first check what will be built

echo ""
echo "pack list:"
echo ""

./modules/pack check
./app/pack check
./notifier/pack check
./assets/pack check

# confirm

echo ""
read -p "press [Enter] to start packing" x
echo ""

# build

./modules/pack build
if [[ $? -ne 0 ]]; then
  exit 1
fi

./app/pack build
if [[ $? -ne 0 ]]; then
  exit 1
fi

./notifier/pack build
if [[ $? -ne 0 ]]; then
  exit 1
fi

./assets/pack build
if [[ $? -ne 0 ]]; then
  exit 1
fi

echo ""
echo "finished packing."
echo ""
