#!/bin/bash

baseDir="$( cd "$(dirname "$0")" && pwd )"
cd "$baseDir"

# first check what will be built

echo ""
echo "pack list:"
echo ""

if [[ $1 == "" || $1 == "js" ]]; then
  ./modules/pack check
  ./assets/pack check
fi

if [[ $1 == "" || $1 == "go" ]]; then
  ./app/pack check
  ./notifier/pack check
fi

# confirm

echo ""
read -p "press [Enter] to start packing" x
echo ""

# build

if [[ $1 == "" || $1 == "js" ]]; then
  ./modules/pack build
  if [[ $? -ne 0 ]]; then
    exit 1
  fi

  ./assets/pack build
  if [[ $? -ne 0 ]]; then
    exit 1
  fi
fi

if [[ $1 == "" || $1 == "go" ]]; then
  ./app/pack build
  if [[ $? -ne 0 ]]; then
    exit 1
  fi

  ./notifier/pack build
  if [[ $? -ne 0 ]]; then
    exit 1
  fi
fi

echo ""
echo "finished packing."
echo ""
